% This is the configuration template file for individual analysis 
% _________________________________________________________________________
% 2009-2012 Stanford Cognitive and Systems Neuroscience Laboratory
%
% $Id: individualstats_config.m.template, Tianwen Chen, 2012-06-06 $
% Yuan Zhang, 2018-02-08,  edited for better compatibility with vsochat
% -------------------------------------------------------------------------

%-Please specify parallel or nonparallel
%-e.g. for individualstats, set to 1 (parallel)
%-for groupstats, set to 0 (nonparallel)
paralist.parallel = '1';

%-Subject list
paralist.subjectlist = '/oak/stanford/groups/menon/scsnlscripts/brainImaging/mri/fmri/preprocessing/spm8/fmrisubjectlist.csv';

%-Run list
paralist.runlist = '/oak/stanford/groups/menon/scsnlscripts/brainImaging/mri/fmri/preprocessing/spm8/runlist.txt'; 
%-Only support 4D nifti.
paralist.data_type = 'nii';

% Please indicate whether to use head movements (1:Yes; 0:No)
paralist.include_mvmnt = 1;

%-Please specify the standard preprocessing pipeline you have used
paralist.pipeline = 'swgcar';

%-Please specify the TR otherwise the default is 2.0 s
paralist.TR = 2.0;

% Please indicate whether it is based on VolRepair pipeline
% 1: use volrepair pipeline data for individual stats
% 0: use standard pipeline data
% If you set volrepair = 1, set up VolRepair section below
% If you set volrepair = 0, do not set up VolRepair section below 
paralist.include_volrepair = 0;

% -------------------------------------------------------------------------
% VolRepair Preprocessing Setup
% -------------------------------------------------------------------------

% Please specify the volrepair preprocessing pipeline
paralist.volpipeline = 'swavr';

% Please specify the volrepair preprocessed folder
paralist.volrepaired_folder = 'volrepair_spm8';

% Please specify the folder for VolRepaired data (swavrI*)
% the stats folder is under 'stats_spm8' folder (generated by default)
paralist.repaired_stats   = 'stats_spm8_VolRepair';



% -------------------------------------------------------------------------
% I/O parameters
% % - Raw data directory (task_degisn folder is under raw data)
% paralist.rawdir = '/oak/stanford/groups/menon/rawdata/scsnl';

% - Project directory - output of the individualstats will be saved in the
% results/taskfmri folder of the project directory
paralist.projectdir = '/oak/stanford/groups/menon/projects/shelbyka/2017_TD_MD_mathfun/';

% Please specify the foler for preprocessed data via standard pipeline
paralist.preprocessed_folder    = 'smoothed_spm8';

% Please specify the folder holding statistics results (below 'stats_spm' 
% which is generated by default)
% If you include_volrepair = 1 below, set stats_folder = 'temp_stats';
paralist.stats_folder = 'comparisondot_swgcar_test0315';
% paralist.stats_folder = 'temp_stats';


% task and contrast parameters
%-Please specify the task design file (*.mat)
paralist.task_dsgn          = 'task_design.mat';

%-Please specify the file holding contrasts
paralist.contrastmat        = 'contrasts_comparisondot.mat';
% paralist.contrastmat = ['']; 


% fMRI parameters
%-spm8 batch templates location
paralist.batchtemplatepath = '/oak/stanford/groups/menon/scsnlscripts/brainImaging/mri/fmri/glmActivation/individualStats/spm8/batchtemplates/';
%-SPM version
paralist.spmversion = 'spm8';

